### ISSUE TITLE
Should't Duration be in seconds?

### ISSUE THREAD

**Issue by lfse-slafleur** [flexiblepower/s2-ws-json#4]
https://github.com/flexiblepower/s2-ws-json/blob/62654ecf429ba5b8acaf4ea6adab0334c2047d09/s2-asyncapi/s2-cem.yaml#L66

In S2 specification Duration is measured in seconds, not milliseconds.

**Comment by lfse-slafleur** [comment]
What do you think? @wilcowijbrandi

**Comment by wilcowijbrandi** [comment]
The S2 specification indeed states it should be seconds (but it doesn't say it should be an integer, so you could have sub-second durations), but we decided to use milliseconds in our s2-ws-json implementation since this is more natural to most programmers.

So for s2-ws-json it should be milliseconds.
