### ISSUE TITLE
FRBC.ActuatorDescription and FRBC.StorageDescription missing "status" field

### ISSUE THREAD

**Issue by tonsmets** [flexiblepower/s2-ws-json#8]
I just noticed the FRBC.ActuatorDescription and FRBC.StorageDescription schemas both are missing the "status" field. Could it be that the generator missed these while converting the S2 specification to json schemas?

**Comment by wilcowijbrandi** [comment]
Hi Ton,

We've decided to remove them from the description messages and put them in their own messages for s2-ws-json ([FRBC.StorageStatus](https://github.com/flexiblepower/s2-ws-json/blob/main/s2-json-schema/messages/FRBC.StorageStatus.schema.json) and [FRBC.ActuatorStatus](https://github.com/flexiblepower/s2-ws-json/blob/main/s2-json-schema/messages/FRBC.ActuatorStatus.schema.json)). This because they are much more dynamic than the 'Description' messages. 

Cheers,
Wilco

**Comment by tonsmets** [comment]
Thank you Wilco! So communicating the StorageStatus and ActuatorStatus should be done apart from the SystemDescription? I can see why you did this indeed as they are very dynamic and will change often. We just need to document this decision.
